spring:
  application:
    name: dailw-judge
  threads:
    virtual:
      enabled: true

server:
  port: 9119

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus

judge:
  pool:
    max-total-per-key: 10
    max-idle-per-key: 5
    max-total: 50
    max-wait: 10s
  thread:
    core-pool-size: 20
    max-pool-size: 40
    queue-capacity: 200
    thread-name-prefix: "judge-exec-"
  sandbox:
    memory-limit: 1073741824 # 1GB
    nano-cpus: 1000000000 # 1 CPU
  compiler:
    time-limit: 10000
    memory-limit: 536870912 # 512MB
  workspace:
    root: "/tmp/dailw-judge/workspace"
